# Generated by Django 3.0.4 on 2020-03-17 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('confirmed', models.IntegerField()),
                ('confirmed_change', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('deaths_change', models.IntegerField()),
                ('state_ranking', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('fips_code', models.IntegerField()),
                ('confirmed', models.IntegerField()),
                ('confirmed_change', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('deaths_change', models.IntegerField()),
                ('county_ranking', models.IntegerField()),
                ('health_agency_data', models.CharField(default='', max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.State')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('city_size', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.County')),
            ],
        ),
    ]
