# Generated by Django 3.0.4 on 2020-03-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('is_subscribed', models.BooleanField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='county.County')),
            ],
        ),
    ]
