# Generated by Django 3.0.4 on 2020-03-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='county_ranking',
        ),
        migrations.AddField(
            model_name='county',
            name='state_county_ranking',
            field=models.CharField(default='[]', max_length=3600),
        ),
        migrations.AlterField(
            model_name='county',
            name='confirmed',
            field=models.CharField(default='[]', max_length=3600),
        ),
        migrations.AlterField(
            model_name='county',
            name='deaths',
            field=models.CharField(default='[]', max_length=3600),
        ),
        migrations.AlterField(
            model_name='state',
            name='confirmed',
            field=models.CharField(default='[]', max_length=3600),
        ),
        migrations.AlterField(
            model_name='state',
            name='deaths',
            field=models.CharField(default='[]', max_length=3600),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_ranking',
            field=models.CharField(default='[]', max_length=3600),
        ),
    ]
