# Generated by Django 3.0.4 on 2020-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
