# Generated by Django 3.0.4 on 2020-03-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0002_auto_20200318_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
