# Generated by Django 3.0.4 on 2020-03-22 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0003_email_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_size',
        ),
    ]
