# Generated by Django 3.0.4 on 2020-03-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='today_delta_confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='county',
            name='today_delta_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='today_delta_confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='today_delta_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
