# Generated by Django 3.0.4 on 2020-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0008_auto_20200325_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='cumulative_hospitalized',
            field=models.CharField(default='[]', max_length=3600),
        ),
    ]
